


corresp_gps <- function() {
  data.table(
    groupe = c("BELLEVILLE 1", "BELLEVILLE 2", "BLAYAIS 1", "BLAYAIS 2",
               "BLAYAIS 3", "BLAYAIS 4", "BUGEY 2", "BUGEY 3", "BUGEY 4",
               "BUGEY 5", "CATTENOM 1", "CATTENOM 2", "CATTENOM 3", "CATTENOM 4",
               "CHINON 1", "CHINON 2", "CHINON 3", "CHINON 4", "CHOOZ 1",
               "CHOOZ 2", "CIVAUX 1", "CIVAUX 2", "CRUAS 1", "CRUAS 2", "CRUAS 3",
               "CRUAS 4", "DAMPIERRE 1", "DAMPIERRE 2", "DAMPIERRE 3",
               "DAMPIERRE 4", "FESSENHEIM 1", "FESSENHEIM 2", "FLAMANVILLE 1",
               "FLAMANVILLE 2", "GOLFECH 1", "GOLFECH 2", "GRAVELINES 1",
               "GRAVELINES 2", "GRAVELINES 3", "GRAVELINES 4", "GRAVELINES 5",
               "GRAVELINES 6", "NOGENT 1", "NOGENT 2", "PALUEL 1", "PALUEL 2", "PALUEL 3",
               "PALUEL 4", "PENLY 1", "PENLY 2", "ST ALBAN 1", "ST ALBAN 2",
               "ST LAURENT 1", "ST LAURENT 2", "TRICASTIN 1", "TRICASTIN 2",
               "TRICASTIN 3", "TRICASTIN 4", "CORDEMAIS 4", "CORDEMAIS 5", "HAVRE 4",
               "PROVENCE 5", "EMILE HUCHET 6", "DK6 - Braek 1",
               "DK6 - Braek 2", "BOUCHAIN 7", "MARTIGUES PONTEAU 5", "MARTIGUES PONTEAU 6",
               "SPEM", "SPEM Pointe", "Grand-Riviere (SPEM)", "CYCOFOS",
               "BLENOD 5", "COMBIGOLFE", "EMILE HUCHET 7", "EMILE HUCHET 8",
               "Croix-de-Metz", "Pont-sur-Sambre", "FR-GA-MORANT1", "GENNEVILLIERS 1",
               "AMFARD14", "AMFARD15", "CORDEMAIS 2", "CORDEMAIS 3",
               "PORCHEVILLE 1", "PORCHEVILLE 2", "PORCHEVILLE 3", "PORCHEVILLE 4",
               "ARAMON 1", "ARAMON 2", "MONTEREAU FIOUL 6", "MONTEREAU FIOUL 5",
               "MONTEREAU GAZ 6", "MONTEREAU GAZ 5", "VAIRES 1", "VAIRES 2",
               "VAIRES 3", "ARRIGHI 1", "ARRIGHI 2", "DIRINON 1", "DIRINON 2",
               "BRENNILIS 1", "BRENNILIS 2", "BRENNILIS 3", "BILHOT01", "FOSCHT 2",
               "Calais Tioxide", "DD HOA 1", "DD HOA 2", "DD HOA DALKIA",
               "DD OA - ELD RESTE France", "DD OA - ERDF RESTE France", "DDBZHT 1",
               "DK6 TV1", "DK6 TV2"),
    code_gp = c("BVIL7T 1", "BVIL7T 2", "BLAYAT 1", "BLAYAT 2", "BLAYAT 3",
                "BLAYAT 4", "BUGEYT 2", "BUGEYT 3", "BUGEYT 4", "BUGEYT 5",
                "CATTET 1", "CATTET 2", "CATTET 3", "CATTET 4", "CHIN2T 1",
                "CHIN2T 2", "CHIN2T 3", "CHIN2T 4", "CHOO2T 1", "CHOO2T 2",
                "CIVAUT 1", "CIVAUT 2", "CRUA5T 1", "CRUA5T 2", "CRUA5T 3", "CRUA5T 4",
                "D.BURT 1", "D.BURT 2", "D.BURT 3", "D.BURT 4", "FESS5T 1",
                "FESS5T 2", "FLAMAT 1", "FLAMAT 2", "GOLF5T 1", "GOLF5T 2",
                "GRAV5T 1", "GRAV5T 2", "GRAV5T 3", "GRAV5T 4", "GRAV5T 5", "GRAV5T 6",
                "N.SE5T 1", "N.SE5T 2", "PALUET 1", "PALUET 2", "PALUET 3",
                "PALUET 4", "PENLYT 1", "PENLYT 2", "SSAL7T 1", "SSAL7T 2",
                "SSEA2T 1", "SSEA2T 2", "TRICAT 1", "TRICAT 2", "TRICAT 3", "TRICAT 4",
                "CORD5T 4", "CORD5T 5", "HAVRET 4", "PROVET 5", "E.HUCT 6", NA,
                NA, "BOUCHT 7", "M.PONT 5", "M.PONT 6", NA, NA, NA, NA,
                "BLENOT 5", NA, "E.HUCT 7", "E.HUCT 8", "C.ME5T01", "SAMBRT1", "MORANT 1",
                "GENN3T 1", "AMFART14", "AMFART15", "CORD5T 2", "CORD5T 3",
                "PORC2T 1", "PORC2T 2", "PORC2T 3", "PORC2T 4", NA, NA, "MTERFT 6",
                "MTERFT 5", "MTERGT 6", "MTERGT 5", "VAIR6T 1", "VAIR6T 2",
                "VAIR6T 3", "ARRI5T 1", "ARRI5T 2", "DIRINT 1", "DIRINT 2",
                "BRENNT 1", "BRENNT 2", "BRENNT 3", NA, NA, "CALAIT1", "DFDC1T 1",
                "DFDC2T 1", "DFDCOT 1", "DFELDT 1", "DFEGST 1", "DDBZHT 1", NA, NA),
    name_desc = c("nuclear_p4", "nuclear_p4", "nuclear_cp0_cp_cp2",
                  "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2",
                  "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2",
                  "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2", "nuclear_p4", "nuclear_p4",
                  "nuclear_p4", "nuclear_p4", "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2",
                  "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2", "nuclear_n4",
                  "nuclear_n4", "nuclear_n4", "nuclear_n4", "nuclear_cp0_cp_cp2",
                  "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2",
                  "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2",
                  "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2",
                  "nuclear_p4", "nuclear_p4", "nuclear_p4", "nuclear_p4",
                  "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2",
                  "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2",
                  "nuclear_p4", "nuclear_p4", "nuclear_p4", "nuclear_p4",
                  "nuclear_p4", "nuclear_p4", "nuclear_p4", "nuclear_p4", "nuclear_p4",
                  "nuclear_p4", "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2",
                  "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2", "nuclear_cp0_cp_cp2",
                  "nuclear_cp0_cp_cp2", "hard_coal_old_1", "hard_coal_old_1",
                  "hard_coal_old_1", "hard_coal_old_1", "hard_coal_old_1", "gas_ccgt_new",
                  "gas_ccgt_new", "gas_ccgt_new", "gas_ccgt_new", "gas_ccgt_new",
                  "gas_ccgt_new", "gas_ccgt_new", "gas_ccgt_new", "gas_ccgt_new",
                  "gas_ccgt_new", "gas_ccgt_new", "gas_ccgt_new", "gas_ccgt_new",
                  "gas_ccgt_new", "gas_ccgt_new", "gas_ccgt_new", "gas_ocgt_old",
                  "gas_cogen_market", "gas_cogen_market", "heavy_oil_old_1",
                  "heavy_oil_old_1", "heavy_oil_old_1", "heavy_oil_old_1",
                  "heavy_oil_old_1", "heavy_oil_old_1", "heavy_oil_old_1", "heavy_oil_old_1",
                  "light_oil", "light_oil", "gas_ocgt_new", "gas_ocgt_new",
                  "light_oil", "light_oil", "light_oil", "light_oil", "light_oil",
                  "light_oil", "light_oil", "light_oil", "light_oil", "light_oil",
                  "gas_cogen_market", "gas_cogen_market", "gas_cogen_market", "light_oil",
                  "light_oil", "light_oil", "light_oil", "light_oil", "light_oil",
                  "gas_ccgt_new", "gas_ccgt_new")
  )
}
